### ISSUE TITLE
楼主您好，请问我增加batch_size报错是什么原因啊？ 谢谢

### ISSUE THREAD

**Issue by wen-flow** [ming71/yolov3-polygon#13]
楼主您好，请问我增加batch_size报错是什么原因啊？ 谢谢
Traceback (most recent call last):
  File "train.py", line 181, in <module>
    main(opt)
  File "train.py", line 116, in main
    loss = model(imgs.to(device), targets, requestPrecision=True)
  File "/home/wen/anaconda3/envs/ryolo/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wen/Documents/object_detection/yolov3-polygon/models.py", line 254, in forward
    metrics[0, i] = (self.losses['TP'][j] > 0).sum().float()  # TP
IndexError: only integers, slices (`:`), ellipsis (`...`), None and long or byte Variables are valid indices (got numpy.float32)

**Comment by ming71** [comment]
建议设置断点查看一下这行的数据是不是None

**Comment by bigKoki** [comment]
建议把计算tp fp这些的代码注释掉，有些问题，注释掉也不影响训练

**Comment by ming71** [comment]
有空你可以注释掉相关代码pr一下，最近我可能没啥时间:smile:

**Comment by bigKoki** [comment]
> 有空你可以注释掉相关代码pr一下，最近我可能没啥时间😄

哈哈 好的，昨天在giantpandacv看到你的文章了

**Comment by ming71** [comment]
对，之前也有关注大熊猫，给推了一下
