### ISSUE TITLE
IndexError: index 1 is out of bounds for dimension 3 with size 1

### ISSUE THREAD

**Issue by ccl-1** [ming71/yolov3-polygon#18]
Traceback (most recent call last):
  File "E:/dl_pkg/yolov3-polygon-master/train.py", line 182, in <module>
    main(opt)
  File "E:/dl_pkg/yolov3-polygon-master/train.py", line 117, in main
    loss = model(imgs.to(device), targets, requestPrecision=True)
  File "E:\Anaconda3\envs\torch1.3\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\dl_pkg\yolov3-polygon-master\models.py", line 237, in forward
    x, *losses = module[0](x, targets, requestPrecision)
  File "E:\Anaconda3\envs\torch1.3\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\dl_pkg\yolov3-polygon-master\models.py", line 151, in forward
    requestPrecision)
  File "E:\dl_pkg\yolov3-polygon-master\utils\utils.py", line 240, in build_targets
    tcls[b, a, gp_y_center, gp_x_center, tc] = 1
IndexError: index 1 is out of bounds for dimension 3 with size 1

Process finished with exit code 1
请问这个是咋回事？，类别是1，数据集标注格式为cls,x1,y1,x2,y2,x3,y3,x4,y4,theta,x,y,w,h

**Comment by ccl-1** [comment]
数据集格式，x1,y1,x2,y2,x3,y3,x4,y4，x,y,w,h 都是原始坐标，没有进行归一化

**Comment by ccl-1** [comment]
我知道错在那里了，数据类别写错了，数据集里面的数据我把它映射到0，1，2这种形式了，换成原始字符串就能训练了。

**Comment by job-yoyo** [comment]
您好，我也遇到了同样的问题，请问下您是如何修改的？

**Comment by abaoji** [comment]
我遇到了跟你一样的问题，但是我按你说的做了还是报错

**Comment by w-Bro** [comment]
@abaoji @ming71 @ccl-1 请问解决了吗，我把类别换成原始字符串还是报错。我的标签格式是class_name,x1,y1,x2,y2,x3,y3,x4,y4，是不是还需要加上theta，lx，ly，w，h，theta是相对于什么的角度,lxly是做左上角的坐标吗？
