### ISSUE TITLE
一个类别训练时报错

### ISSUE THREAD

**Issue by abaoji** [ming71/yolov3-polygon#24]
自己创建了一个数据集，只有一个类别，按照教程改了相关参数设置训练时报错。但是把相关参数设置成两个类别的就没有错可以训练。报错如下：Traceback (most recent call last):   File "/home/xuebq/Desktop/yolov3-polygon-master/train.py", line 182, in <module>     main(opt)   File "/home/xuebq/Desktop/yolov3-polygon-master/train.py", line 117, in main     loss = model(imgs.to(device), targets, requestPrecision=True)   File "/home/xuebq/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl     result = self.forward(*input, **kwargs)   File "/home/xuebq/Desktop/yolov3-polygon-master/models.py", line 235, in forward     x, *losses = module[0](x, targets, requestPrecision)   File "/home/xuebq/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl     result = self.forward(*input, **kwargs)   File "/home/xuebq/Desktop/yolov3-polygon-master/models.py", line 148, in forward     build_targets(pred_boxes, pred_conf, pred_cls, targets, self.scaled_anchors, self.nA, self.nC, nG,   File "/home/xuebq/Desktop/yolov3-polygon-master/utils/utils.py", line 240, in build_targets     tcls[b, a, gp_y_center, gp_x_center, tc] = 1 IndexError: index 1 is out of bounds for dimension 3 with size 1

**Comment by HaochenZ11** [comment]
Hi, have you solved this problem?
